# Generated by Django 4.1.4 on 2023-11-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombrecompleto', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(default='', max_length=50)),
                ('contrasenia', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
