# Generated by Django 4.1.4 on 2023-11-08 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('idconductor', models.CharField(default=1, max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=20)),
                ('puntuacion', models.CharField(max_length=3)),
                ('correo', models.CharField(default='', max_length=50)),
                ('contrasenia', models.CharField(default='', max_length=20)),
                ('vehiculo', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='viaje',
            fields=[
                ('idviaje', models.CharField(default=1, max_length=3, primary_key=True, serialize=False)),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=20)),
                ('termino', models.CharField(max_length=20)),
                ('percio', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=50)),
                ('calificacion', models.CharField(default=0, max_length=3)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.conductor')),
            ],
            options={
                'db_table': 'viaje',
            },
        ),
    ]
