# Generated by Django 4.1.4 on 2023-11-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_conductor_viaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='conductor',
            new_name='Conductor',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='percio',
            new_name='precio',
        ),
    ]
