# Generated by Django 4.1.4 on 2023-11-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_viaje_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='calificacion',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='idviaje',
            field=models.CharField(default='', max_length=3, primary_key=True, serialize=False),
        ),
    ]
