# Generated by Django 4.1.4 on 2023-11-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_viaje_calificacion_alter_viaje_idviaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='Conductor',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='calificacion',
        ),
    ]
