# Generated by Django 4.1.4 on 2023-11-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_viaje_conductor_remove_viaje_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='calificacion',
            field=models.CharField(default='', max_length=3),
        ),
    ]
